version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./back/data:/app/data
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && node dist/index.js"

volumes:
  db_data:
